### ISSUE TITLE
2019 Update

### ISSUE THREAD

**Issue by chintanp** [chiehrosswang/TRB_MSWORD#1]
Any plans to update the template for this year if any changes are needed?

Thanks

**Comment by chiehrosswang** [comment]
@chintanp just did.  Not much has changed since last year.  I feel that the guidelines just became loose - certain formatting details have been left out in [this year's guidelines](http://onlinepubs.trb.org/onlinepubs/am/infoforauthors.pdf).  If you see anything that needs to be updated, please let me know.  Thanks.

**Comment by chintanp** [comment]
@chiehrosswang One minor edit could be the title - **No** ALL CAPS, each word capitalized except preposition, articles etc.
